# Generated by Django 5.2.15 on 2026-06-29 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loyalty", "0003_remove_referral_code"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loyaltyaccount",
            options={},
        ),
        migrations.AlterModelOptions(
            name="referral",
            options={},
        ),
        migrations.AlterField(
            model_name="loyaltytransaction",
            name="source",
            field=models.CharField(
                choices=[
                    ("referral", "Referral Bonus"),
                    ("redemption", "Points Redemption"),
                    ("bonus", "Bonus"),
                    ("penalty", "Cancellation Penalty"),
                ],
                max_length=20,
            ),
        ),
    ]
