# Generated by Django 5.2.14 on 2026-05-30 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0008_user_suspension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='admin_assigned_city',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
