# Generated by Django 5.2.14 on 2026-05-17 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="subcategory",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
