# Generated by Django 5.2.14 on 2026-06-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_previous_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'stock_quantity'], name='variant_product_stock_idx'),
        ),
    ]
