# Generated by Django 5.2.14 on 2026-06-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='accepts_custom_orders',
            field=models.BooleanField(default=False, help_text='Artisan/made-to-order toggle — disables stock tracking for this variant'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What vendor paid — used in stock value reports, never shown to customers', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Alert vendor when stock drops to or below this number'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum Retail Price — shown to customers as crossed-out price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='reorder_point',
            field=models.PositiveIntegerField(blank=True, help_text='Separate reorder alert threshold', null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='show_stock_count',
            field=models.BooleanField(default=True, help_text='Vendor toggle — hide stock count from vendor website if False'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('inactive', 'Inactive'), ('out_of_stock', 'Out of Stock'), ('blacklisted', 'Blacklisted')], default='draft', max_length=20),
        ),
    ]
