# Generated by Django 5.2.15 on 2026-07-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_add_blacklisted_status_and_inventory_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockwatchlist",
            name="notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
