from django.core.management.base import BaseCommand
from apps.locations.models import LocationMaster

# Complete India location data — all 36 states/UTs, all districts, major cities
INDIA_LOCATIONS = {
    # ── Andhra Pradesh (26 districts post-2022 reorganisation) ──────────────
    "Andhra Pradesh": {
        "Srikakulam":                    ["Srikakulam", "Narasannapeta", "Palasa", "Amadalavalasa", "Rajam", "Tekkali"],
        "Vizianagaram":                  ["Vizianagaram", "Bobbili", "Parvathipuram", "Salur", "Bheemunipatnam"],
        "Parvathipuram Manyam":          ["Parvathipuram", "Salur", "Makkuva", "Kurupam"],
        "Alluri Sitharama Raju":         ["Paderu", "Chintapalli", "Addateegala", "Rampachodavaram"],
        "Anakapalli":                    ["Anakapalli", "Yelamanchili", "Chodavaram", "Narsipatnam"],
        "Visakhapatnam":                 ["Visakhapatnam", "Gajuwaka", "MVP Colony", "Bheemunipatnam", "Madhurawada", "Rushikonda", "Duvvada", "Kommadi"],
        "Kakinada":                      ["Kakinada", "Peddapuram", "Tuni", "Prathipadu", "Samalkot"],
        "East Godavari":                 ["Rajahmundry", "Kovvur", "Nidadavolu", "Bhimavaram (E)", "Mandapeta"],
        "Dr. B.R. Ambedkar Konaseema":  ["Amalapuram", "Razole", "Mummidivaram", "Ravulapalem"],
        "West Godavari":                 ["Eluru", "Bhimavaram", "Narsapuram", "Tanuku", "Palakol", "Kovvur"],
        "Eluru":                         ["Eluru", "Nuzvid", "Denduluru", "Unguturu"],
        "NTR":                           ["Vijayawada", "Nandigama", "Gudivada", "Jaggaiahpet", "Tiruvuru"],
        "Krishna":                       ["Machilipatnam", "Bandar", "Gudivada", "Pedana", "Movva"],
        "Bapatla":                       ["Bapatla", "Chirala", "Narasaraopet (E)", "Repalle", "Vetapalem"],
        "Guntur":                        ["Guntur", "Tenali", "Mangalagiri", "Narasaraopet", "Sattenapalle", "Ponnur", "Tadepalligudem"],
        "Palnadu":                       ["Narasaraopet", "Macherla", "Gurazala", "Dachepalle", "Vinukonda"],
        "Prakasam":                      ["Ongole", "Markapur", "Kandukur", "Giddalur", "Darsi", "Chimakurthy"],
        "Sri Potti Sriramulu Nellore":   ["Nellore", "Kavali", "Gudur", "Sullurpeta", "Atmakur", "Allur"],
        "Kurnool":                       ["Kurnool", "Adoni", "Dhone", "Yemmiganur", "Pattikonda", "Allagadda"],
        "Nandyal":                       ["Nandyal", "Atmakur (K)", "Bethamcherla", "Srisailam", "Banaganapalle"],
        "Anantapur":                     ["Anantapur", "Hindupur", "Guntakal", "Tadipatri", "Kadiri", "Dharmavaram", "Rayadurgam"],
        "Sri Sathya Sai":                ["Puttaparthi", "Penukonda", "Madakasira", "Hindupur (N)", "Lepakshi"],
        "YSR":                           ["Kadapa", "Proddatur", "Badvel", "Rajampet", "Jammalamadugu", "Mydukur"],
        "Annamayya":                     ["Rajampet", "Rayachoti", "Pulivendula", "Kamalapuram", "Pakala"],
        "Tirupati":                      ["Tirupati", "Srikalahasti", "Puttur", "Venkatagiri", "Sullurpeta (S)"],
        "Chittoor":                      ["Chittoor", "Madanapalle", "Kuppam", "Punganur", "Palamaner", "Pileru"],
    },

    # ── Telangana (33 districts) ─────────────────────────────────────────────
    "Telangana": {
        "Hyderabad":              ["Hyderabad", "Secunderabad", "Abids", "Banjara Hills", "Jubilee Hills", "Gachibowli", "Kondapur", "Madhapur", "Hitec City", "Begumpet", "Ameerpet", "Kukatpally", "Himayatnagar", "Mehdipatnam", "Lakdikapul"],
        "Rangareddy":             ["LB Nagar", "Dilsukhnagar", "Uppal", "Hayathnagar", "Maheshwaram", "Shadnagar", "Tandur", "Rajendranagar", "Saroornagar"],
        "Medchal-Malkajgiri":     ["Malkajgiri", "Kompally", "Medchal", "Alwal", "Quthbullapur", "Balanagar", "Dundigal", "Secunderabad Cantonment"],
        "Sangareddy":             ["Sangareddy", "Patancheru", "Zahirabad", "Andole", "Jogipet", "Sadasivpet"],
        "Siddipet":               ["Siddipet", "Gajwel", "Husnabad", "Dubbaka", "Chinnakodur"],
        "Vikarabad":              ["Vikarabad", "Tandur", "Parigi", "Kodangal", "Marpalle"],
        "Yadadri Bhuvanagiri":    ["Bhongir", "Yadagirigutta", "Choutuppal", "Mothkur", "Alair"],
        "Suryapet":               ["Suryapet", "Nalgonda (S)", "Kodad", "Huzurnagar", "Neredcherla"],
        "Nalgonda":               ["Nalgonda", "Miryalaguda", "Nakrekal", "Devarakonda", "Chityal"],
        "Mahabubabad":            ["Mahabubabad", "Thorrur", "Dornakal", "Kesamudram"],
        "Bhadradri Kothagudem":   ["Kothagudem", "Bhadrachalam", "Palwancha", "Yellandu", "Manuguru"],
        "Khammam":                ["Khammam", "Wyra", "Sathupally", "Madhira", "Kallur"],
        "Warangal Urban":         ["Warangal", "Hanamkonda", "Kazipet", "Dharmasagar", "Hasanparthy"],
        "Warangal Rural":         ["Narsampet", "Parkal", "Ghanpur", "Atmakur", "Nekkonda"],
        "Mulugu":                 ["Mulugu", "Mangapet", "Wazeedu", "Eturnagaram"],
        "Jangaon":                ["Jangaon", "Devaruppula", "Bachannapeta", "Zaffergadh"],
        "Jayashankar Bhupalpally": ["Bhupalpalle", "Manthani", "Mahadevpur", "Chityal (J)"],
        "Peddapalli":             ["Peddapalli", "Manthani", "Ramagundam", "Godavarikhani", "Sultanabad"],
        "Karimnagar":             ["Karimnagar", "Huzurabad", "Choppadandi", "Yellareddypet"],
        "Rajanna Sircilla":       ["Sircilla", "Vemulawada", "Konaraopet", "Yellareddypet (R)"],
        "Jagtial":                ["Jagtial", "Metpally", "Raikal", "Koratla", "Dharmapuri"],
        "Nirmal":                 ["Nirmal", "Bhainsa", "Mudhole", "Sarangapur"],
        "Mancherial":             ["Mancherial", "Bellampalli", "Chennur", "Naspur"],
        "Komaram Bheem Asifabad": ["Asifabad", "Sirpur", "Kagaznagar"],
        "Adilabad":               ["Adilabad", "Tandur (A)", "Mavala", "Bazarhatnoor"],
        "Kamareddy":              ["Kamareddy", "Banswada", "Yellareddy", "Domakonda"],
        "Nizamabad":              ["Nizamabad", "Bodhan", "Armoor", "Dichpally", "Balkonda"],
        "Medak":                  ["Medak", "Toopran", "Narsapur", "Shankarampet", "Siddipet (M)"],
        "Narayanpet":             ["Narayanpet", "Makthal", "Narva", "Utkur"],
        "Jogulamba Gadwal":       ["Gadwal", "Alampur", "Makthal (J)", "Dharur"],
        "Wanaparthy":             ["Wanaparthy", "Pebbair", "Gopalpet", "Kalwakurthy"],
        "Nagarkurnool":           ["Nagarkurnool", "Kollapur", "Achampet", "Kalwakurthy (N)", "Srisailam (T)"],
        "Mahbubnagar":            ["Mahbubnagar", "Jadcherla", "Shadnagar (M)", "Kosgi", "Balanagar (M)"],
    },

    # ── Karnataka (31 districts) ─────────────────────────────────────────────
    "Karnataka": {
        "Bengaluru Urban":    ["Bengaluru", "Koramangala", "Whitefield", "Electronic City", "Hebbal", "Jayanagar", "JP Nagar", "Marathahalli", "HSR Layout", "Indiranagar", "Yelahanka", "Rajajinagar", "Banashankari", "BTM Layout", "Malleshwaram"],
        "Bengaluru Rural":    ["Devanahalli", "Doddaballapur", "Hoskote", "Nelamangala", "Channapatna"],
        "Ramanagara":         ["Ramanagara", "Channapatna", "Kanakapura", "Magadi"],
        "Chikkaballapur":     ["Chikkaballapur", "Chintamani", "Gudibande", "Sidlaghatta", "Gauribidanur"],
        "Kolar":              ["Kolar", "KGF (Kolar Gold Fields)", "Bangarapet", "Mulbagal", "Srinivaspur"],
        "Tumkur":             ["Tumkur", "Tiptur", "Gubbi", "Sira", "Madhugiri", "Pavagada"],
        "Mandya":             ["Mandya", "Maddur", "Malavalli", "Srirangapatna", "Nagamangala"],
        "Mysuru":             ["Mysuru", "Nanjangud", "T Narasipura", "Hunsur", "K R Nagar", "Periyapatna"],
        "Chamarajanagar":     ["Chamarajanagar", "Gundlupet", "Kollegal", "Yelandur"],
        "Hassan":             ["Hassan", "Arsikere", "Belur", "Sakleshpur", "Holenarasipur", "Alur"],
        "Kodagu":             ["Madikeri", "Somwarpet", "Virajpet", "Kushalnagar", "Ponnampet"],
        "Chikkamagaluru":     ["Chikkamagaluru", "Mudigere", "Tarikere", "Koppa", "Kadur", "Sringeri"],
        "Shivamogga":         ["Shivamogga", "Bhadravati", "Sagar", "Thirthahalli", "Shikaripura", "Hosanagar"],
        "Uttara Kannada":     ["Karwar", "Sirsi", "Kumta", "Bhatkal", "Ankola", "Yellapur", "Mundgod"],
        "Dakshina Kannada":   ["Mangaluru", "Puttur", "Bantwal", "Sullia", "Belthangady", "Moodabidri"],
        "Udupi":              ["Udupi", "Manipal", "Kundapura", "Brahmavar", "Karkala", "Hebri"],
        "Belagavi":           ["Belagavi", "Gokak", "Bailhongal", "Khanapur", "Ramdurg", "Chikkodi"],
        "Dharwad":            ["Dharwad", "Hubli", "Alnavar", "Kalghatgi", "Navalgund"],
        "Gadag":              ["Gadag", "Betgeri", "Nargund", "Ron", "Shirhatti", "Mundargi"],
        "Haveri":             ["Haveri", "Ranebennur", "Savanur", "Byadgi", "Hirekerur"],
        "Vijayapura":         ["Vijayapura", "Muddebihal", "Basavana Bagewadi", "Sindagi", "Indi", "Talikot"],
        "Bidar":              ["Bidar", "Basavakalyan", "Bhalki", "Humanabad", "Aurad"],
        "Kalaburagi":         ["Kalaburagi", "Sedam", "Aland", "Chittapur", "Yadgir (K)", "Chincholi"],
        "Yadgir":             ["Yadgir", "Shahpur", "Shorapur", "Gurmitkal", "Hunasagi"],
        "Raichur":            ["Raichur", "Manvi", "Lingasugur", "Sindhanur", "Devadurga", "Maski"],
        "Koppal":             ["Koppal", "Gangavathi", "Kushtagi", "Yelburga"],
        "Ballari":            ["Ballari", "Hospet", "Sandur", "Kampli", "Siruguppa"],
        "Vijayanagara":       ["Hosapete", "Harapanahalli", "Hagaribommanahalli", "Hadagalli"],
        "Chitradurga":        ["Chitradurga", "Challakere", "Holalkere", "Molakalmuru", "Hiriyur"],
        "Davanagere":         ["Davanagere", "Harihar", "Channagiri", "Honnali", "Harpanahalli"],
        "Bagalkot":           ["Bagalkot", "Badami", "Mudhol", "Jamkhandi", "Ilkal", "Hungund"],
    },

    # ── Maharashtra (36 districts) ───────────────────────────────────────────
    "Maharashtra": {
        "Mumbai City":        ["Fort", "Colaba", "Dadar", "Byculla", "Worli", "Parel", "Sewri", "Mazgaon"],
        "Mumbai Suburban":    ["Andheri", "Bandra", "Borivali", "Kandivali", "Malad", "Goregaon", "Jogeshwari", "Vile Parle", "Kurla", "Ghatkopar", "Vikhroli", "Chembur", "Mulund", "Powai"],
        "Thane":              ["Thane", "Kalyan", "Dombivli", "Ulhasnagar", "Bhiwandi", "Mira-Bhayander", "Ambernath", "Badlapur", "Titwala"],
        "Palghar":            ["Palghar", "Vasai-Virar", "Boisar", "Dahanu", "Talasari", "Manor"],
        "Raigad":             ["Alibag", "Pen", "Panvel", "Khopoli", "Karjat", "Uran", "Mahad"],
        "Ratnagiri":          ["Ratnagiri", "Chiplun", "Khed", "Sangameshwar", "Dapoli", "Guhagar"],
        "Sindhudurg":         ["Sindhudurg", "Kudal", "Sawantwadi", "Malvan", "Vengurla", "Devgad"],
        "Pune":               ["Pune", "Pimpri-Chinchwad", "Kothrud", "Hinjewadi", "Hadapsar", "Baner", "Kharadi", "Wakad", "Viman Nagar", "Katraj", "Dehu Road", "Talegaon", "Shirur", "Baramati"],
        "Satara":             ["Satara", "Karad", "Wai", "Panchgani", "Mahabaleshwar", "Khatav"],
        "Sangli":             ["Sangli", "Miraj", "Kupwad", "Islampur", "Shirala", "Tasgaon"],
        "Kolhapur":           ["Kolhapur", "Ichalkaranji", "Kagal", "Hatkanangle", "Radhanagari"],
        "Solapur":            ["Solapur", "Pandharpur", "Barshi", "Akkalkot", "Mangalvedhe"],
        "Nashik":             ["Nashik", "Malegaon", "Niphad", "Sinnar", "Dindori", "Igatpuri", "Tryambakeshwar"],
        "Dhule":              ["Dhule", "Shirpur", "Sakri", "Sindkheda"],
        "Nandurbar":          ["Nandurbar", "Shahada", "Taloda", "Navapur", "Akkalkuwa"],
        "Jalgaon":            ["Jalgaon", "Bhusawal", "Amalner", "Yawal", "Pachora", "Bodwad"],
        "Aurangabad":         ["Aurangabad", "Paithan", "Kannad", "Gangapur", "Sillod", "Khuldabad"],
        "Jalna":              ["Jalna", "Ambad", "Partur", "Bhokardan", "Mantha"],
        "Beed":               ["Beed", "Ambejogai", "Parli", "Majalgaon", "Ashti", "Georai"],
        "Osmanabad":          ["Osmanabad", "Tuljapur", "Lohara", "Omerga", "Kalamb", "Paranda"],
        "Latur":              ["Latur", "Udgir", "Nilanga", "Ausa", "Deoni", "Chakur"],
        "Nanded":             ["Nanded", "Kinwat", "Loha", "Biloli", "Ardhapur", "Mukhed", "Hadgaon"],
        "Hingoli":            ["Hingoli", "Basmath", "Sengaon", "Kalamnuri"],
        "Parbhani":           ["Parbhani", "Pathri", "Jintur", "Gangakhed", "Manwath"],
        "Nagpur":             ["Nagpur", "Wardha", "Kamptee", "Hingna", "Butibori", "Umred"],
        "Wardha":             ["Wardha", "Hinganghat", "Arvi", "Sewagram", "Karanja"],
        "Yavatmal":           ["Yavatmal", "Pusad", "Wani", "Pandarkawada", "Ghatanji"],
        "Amravati":           ["Amravati", "Achalpur", "Daryapur", "Warud", "Morshi"],
        "Akola":              ["Akola", "Washim", "Murtizapur", "Akot", "Balapur"],
        "Washim":             ["Washim", "Risod", "Manora", "Karanja (W)", "Malegaon (W)"],
        "Buldhana":           ["Buldhana", "Khamgaon", "Malkapur", "Chikhli", "Mehkar"],
        "Chandrapur":         ["Chandrapur", "Warora", "Mul", "Bhadravati", "Rajura"],
        "Gadchiroli":         ["Gadchiroli", "Aheri", "Chamorshi", "Kurkheda", "Etapalli"],
        "Gondia":             ["Gondia", "Tirora", "Arjuni Morgaon", "Sadak-Arjuni"],
        "Bhandara":           ["Bhandara", "Tumsar", "Mohadi", "Sakoli", "Lakhandur"],
        "Raigad":             ["Alibag", "Pen", "Panvel", "Mahad", "Roha", "Murud"],
    },

    # ── Tamil Nadu (38 districts) ────────────────────────────────────────────
    "Tamil Nadu": {
        "Chennai":          ["Chennai", "T Nagar", "Anna Nagar", "Adyar", "Velachery", "Tambaram", "Perambur", "Egmore", "Mylapore", "Guindy", "Chromepet", "Sholinganallur", "Pallavaram", "Ambattur", "Avadi"],
        "Tiruvallur":       ["Tiruvallur", "Avadi", "Ambattur", "Ponneri", "Gummidipoondi", "Thiruvallur"],
        "Chengalpattu":     ["Chengalpattu", "Maraimalai Nagar", "Maduranthakam", "Tambaram (S)", "Vandalur"],
        "Kancheepuram":     ["Kancheepuram", "Sriperumbudur", "Uthiramerur", "Walajabad"],
        "Ranipet":          ["Ranipet", "Arcot", "Walajapet", "Arani"],
        "Vellore":          ["Vellore", "Ambur", "Gudiyatham", "Vaniyambadi", "Jolarpet"],
        "Tirupattur":       ["Tirupattur", "Natrampalli", "Jolarpettai", "Ambur (T)"],
        "Krishnagiri":      ["Krishnagiri", "Hosur", "Denkanikotta", "Uthangarai", "Pochampalli"],
        "Dharmapuri":       ["Dharmapuri", "Palacode", "Pennagaram", "Harur", "Nammakkal (D)"],
        "Salem":            ["Salem", "Mettur", "Omalur", "Yercaud", "Attur", "Edappadi"],
        "Namakkal":         ["Namakkal", "Rasipuram", "Sankari", "Tiruchengode", "Kumarapalayam"],
        "Erode":            ["Erode", "Bhavani", "Gobichettipalayam", "Pallipalayam", "Sathyamangalam", "Perundurai"],
        "Tiruppur":         ["Tiruppur", "Udumalaipettai", "Palladam", "Dharapuram", "Kangayam"],
        "Coimbatore":       ["Coimbatore", "Pollachi", "Mettupalayam", "Gudalur", "Annur", "Sulur"],
        "Nilgiris":         ["Ooty", "Coonoor", "Kotagiri", "Gudalur"],
        "Dindigul":         ["Dindigul", "Oddanchatram", "Palani", "Natham", "Vedasandur"],
        "Theni":            ["Theni", "Bodinayakkanur", "Periyakulam", "Uthamapalayam"],
        "Madurai":          ["Madurai", "Melur", "Usilampatti", "Thirumangalam", "Vadipatti"],
        "Virudhunagar":     ["Virudhunagar", "Aruppukkottai", "Sivakasi", "Rajapalayam", "Sattur", "Srivilliputtur"],
        "Sivaganga":        ["Sivaganga", "Karaikudi", "Devakottai", "Ilayangudi"],
        "Ramanathapuram":   ["Ramanathapuram", "Paramakudi", "Rameswaram", "Mandapam", "Mudukulathur"],
        "Thoothukudi":      ["Thoothukudi", "Kovilpatti", "Tiruchendur", "Kayalpatnam", "Srivaikundam"],
        "Tirunelveli":      ["Tirunelveli", "Palayamkottai", "Ambasamudram", "Nanguneri"],
        "Tenkasi":          ["Tenkasi", "Shencottah", "Sankarankovil", "Alangulam"],
        "Kanyakumari":      ["Nagercoil", "Kanyakumari", "Padmanabhapuram", "Colachel", "Kuzhithurai"],
        "Tiruchirappalli":  ["Tiruchirappalli", "Lalgudi", "Musiri", "Srirangam", "Manachanallur"],
        "Perambalur":       ["Perambalur", "Veppanthattai", "Ariyalur (P)"],
        "Ariyalur":         ["Ariyalur", "Jayankondam", "Sendurai", "Udayarpalayam"],
        "Karur":            ["Karur", "Kulithalai", "Manapparai", "Aravakurichi"],
        "Pudukkottai":      ["Pudukkottai", "Karaikudi (P)", "Aranthangi", "Thirumayam", "Iluppur"],
        "Thanjavur":        ["Thanjavur", "Kumbakonam", "Papanasam", "Pattukkottai", "Orathanadu"],
        "Tiruvarur":        ["Tiruvarur", "Nagapattinam", "Mannargudi", "Nannilam"],
        "Nagapattinam":     ["Nagapattinam", "Mayiladuthurai", "Sirkazhi", "Poompuhar"],
        "Mayiladuthurai":   ["Mayiladuthurai", "Sirkazhi", "Sirkali", "Kollidam"],
        "Cuddalore":        ["Cuddalore", "Chidambaram", "Panruti", "Neyveli", "Virudhachalam"],
        "Villupuram":       ["Villupuram", "Gingee", "Tindivanam", "Vanur", "Ulundurpettai"],
        "Kallakurichi":     ["Kallakurichi", "Sankarapuram", "Chinnasalem", "Ulundurpettai (K)"],
        "Tiruvannamalai":   ["Tiruvannamalai", "Polur", "Arani (T)", "Cheyyar", "Vandavasi"],
    },

    # ── Kerala (14 districts) ────────────────────────────────────────────────
    "Kerala": {
        "Thiruvananthapuram": ["Thiruvananthapuram", "Neyyattinkara", "Varkala", "Nedumangad", "Attingal", "Kazhakoottam"],
        "Kollam":             ["Kollam", "Punalur", "Karunagappally", "Kottarakkara", "Pathanapuram"],
        "Pathanamthitta":     ["Pathanamthitta", "Adoor", "Thiruvalla", "Ranni", "Konni"],
        "Alappuzha":          ["Alappuzha", "Cherthala", "Haripad", "Kayamkulam", "Ambalappuzha"],
        "Kottayam":           ["Kottayam", "Changanacherry", "Pala", "Ettumanoor", "Vaikom", "Thodupuzha (K)"],
        "Idukki":             ["Idukki", "Thodupuzha", "Munnar", "Kattappana", "Adimali"],
        "Ernakulam":          ["Kochi", "Ernakulam", "Aluva", "Perumbavoor", "Muvattupuzha", "Angamaly", "North Paravur", "Kalamassery", "Tripunithura"],
        "Thrissur":           ["Thrissur", "Chalakudy", "Guruvayur", "Irinjalakuda", "Kodungallur", "Kunnamkulam"],
        "Palakkad":           ["Palakkad", "Ottappalam", "Shornur", "Mannarkkad", "Chittur", "Pattambi"],
        "Malappuram":         ["Malappuram", "Manjeri", "Perinthalmanna", "Tirur", "Kondotty", "Ponnani", "Tirurrangadi"],
        "Kozhikode":          ["Kozhikode", "Vadakara", "Koyilandy", "Ramanattukara", "Feroke", "Balussery"],
        "Wayanad":            ["Kalpetta", "Mananthavady", "Sulthan Bathery", "Vythiri", "Ambalavayal"],
        "Kannur":             ["Kannur", "Thalassery", "Payyannur", "Iritty", "Mattannur"],
        "Kasaragod":          ["Kasaragod", "Kanhangad", "Hosdurg", "Nileshwar", "Bekal"],
    },

    # ── Gujarat (33 districts) ───────────────────────────────────────────────
    "Gujarat": {
        "Ahmedabad":              ["Ahmedabad", "Sanand", "Dholka", "Bavla", "Viramgam", "Dhandhuka"],
        "Gandhinagar":            ["Gandhinagar", "Kalol", "Mansa", "Dehgam"],
        "Anand":                  ["Anand", "Vallabh Vidyanagar", "Khambhat", "Petlad", "Nadiad (A)"],
        "Kheda":                  ["Kheda", "Nadiad", "Kapadvanj", "Matar", "Thasra"],
        "Mahisagar":              ["Lunawada", "Santrampur", "Balasinor", "Virpur"],
        "Aravalli":               ["Modasa", "Dhansura", "Bayad", "Malpur"],
        "Sabarkantha":            ["Himmatnagar", "Idar", "Prantij", "Talod"],
        "Banaskantha":            ["Palanpur", "Deesa", "Tharad", "Dhanera", "Radhanpur"],
        "Patan":                  ["Patan", "Sidhpur", "Chanasma", "Radhanpur (P)"],
        "Mehsana":                ["Mehsana", "Unjha", "Visnagar", "Kheralu", "Becharaji"],
        "Surendranagar":          ["Surendranagar", "Wadhwan", "Chotila", "Thangadh", "Limbdi"],
        "Rajkot":                 ["Rajkot", "Gondal", "Jetpur", "Upleta", "Wankaner"],
        "Morbi":                  ["Morbi", "Wankaner (M)", "Tankara", "Halvad"],
        "Jamnagar":               ["Jamnagar", "Khambhalia", "Jodia"],
        "Devbhoomi Dwarka":       ["Dwarka", "Okha", "Salaya"],
        "Porbandar":              ["Porbandar", "Ranavav", "Chudasama"],
        "Junagadh":               ["Junagadh", "Keshod", "Veraval (J)", "Mangrol", "Visavadar"],
        "Gir Somnath":            ["Veraval", "Somnath", "Una", "Talala"],
        "Amreli":                 ["Amreli", "Rajula", "Savarkundla", "Babra"],
        "Bhavnagar":              ["Bhavnagar", "Palitana", "Botad", "Sihor", "Ghogha"],
        "Botad":                  ["Botad", "Gadhada", "Barwala"],
        "Kutch":                  ["Bhuj", "Gandhidham", "Mundra", "Anjar", "Adipur", "Mandvi"],
        "Surat":                  ["Surat", "Bardoli", "Navsari", "Vyara (S)", "Mandvi (S)", "Mangrol (S)"],
        "Tapi":                   ["Vyara", "Ukai", "Songadh", "Kukarmunda"],
        "Navsari":                ["Navsari", "Gandevi", "Chikhli", "Bilimora"],
        "Valsad":                 ["Valsad", "Vapi", "Bilimora (V)", "Pardi", "Umbergaon"],
        "Dang":                   ["Ahwa", "Waghai"],
        "Narmada":                ["Rajpipla", "Tilakwada", "Dediapada", "Sagbara"],
        "Bharuch":                ["Bharuch", "Ankleshwar", "Hansot", "Vagra", "Jambusar"],
        "Vadodara":               ["Vadodara", "Dabhoi", "Padra", "Karjan", "Savli"],
        "Panchmahal":             ["Godhra", "Halol", "Lunawada (P)", "Dahod (P)", "Kalol (P)"],
        "Dahod":                  ["Dahod", "Limkheda", "Devgadhbaria", "Fatepura"],
        "Chota Udaipur":          ["Chota Udaipur", "Kawant", "Naswadi", "Sankheda"],
    },

    # ── Rajasthan (33 districts) ─────────────────────────────────────────────
    "Rajasthan": {
        "Ajmer":             ["Ajmer", "Pushkar", "Kishangarh", "Beawar", "Nasirabad"],
        "Alwar":             ["Alwar", "Bhiwadi", "Rajgarh", "Tijara", "Ramgarh"],
        "Banswara":          ["Banswara", "Gagron", "Ghatol", "Kushalgarh"],
        "Baran":             ["Baran", "Anta", "Shahabad", "Kelwara"],
        "Barmer":            ["Barmer", "Balotra", "Sheo", "Pachpadra", "Gudamalani"],
        "Bharatpur":         ["Bharatpur", "Deeg", "Nadbai", "Bayana", "Weir"],
        "Bhilwara":          ["Bhilwara", "Shahpura", "Gulabpura", "Mandal", "Asind"],
        "Bikaner":           ["Bikaner", "Nokha", "Kolayat", "Lunkaransar", "Pugal"],
        "Bundi":             ["Bundi", "Hindoli", "Lakheri", "Nainwa"],
        "Chittorgarh":       ["Chittorgarh", "Rawatbhata", "Nimbahera", "Bari Sadri"],
        "Churu":             ["Churu", "Sujangarh", "Sardarshahar", "Ratangarh", "Taranagar"],
        "Dausa":             ["Dausa", "Bandikui", "Sikrai", "Mahwa", "Lalsot"],
        "Dholpur":           ["Dholpur", "Bari", "Baseri", "Saipau"],
        "Dungarpur":         ["Dungarpur", "Sagwara", "Bichhiwara", "Aspur"],
        "Hanumangarh":       ["Hanumangarh", "Bhadra", "Nohar", "Sangaria", "Pilibanga"],
        "Jaipur":            ["Jaipur", "Chomu", "Dudu", "Amer", "Sanganer", "Bassi"],
        "Jaisalmer":         ["Jaisalmer", "Pokaran", "Ramgarh", "Fatehgarh"],
        "Jalore":            ["Jalore", "Bhinmal", "Sanchore", "Ahore", "Siwana"],
        "Jhalawar":          ["Jhalawar", "Jhalrapatan", "Manohar Thana", "Khanpur"],
        "Jhunjhunu":         ["Jhunjhunu", "Pilani", "Chirawa", "Nawalgarh", "Mandawa"],
        "Jodhpur":           ["Jodhpur", "Pali (J)", "Osian", "Bilara", "Balesar"],
        "Karauli":           ["Karauli", "Hindaun City", "Sapotra", "Mandrayal"],
        "Kota":              ["Kota", "Ramganj Mandi", "Sangod", "Itawa"],
        "Nagaur":            ["Nagaur", "Merta City", "Didwana", "Makrana", "Nawa"],
        "Pali":              ["Pali", "Sojat", "Marwar Junction", "Jaitaran", "Raipur (R)"],
        "Pratapgarh":        ["Pratapgarh", "Arnod", "Chhoti Sadri", "Dhariyawad"],
        "Rajsamand":         ["Rajsamand", "Nathdwara", "Railmagra", "Kumbhalgarh"],
        "Sawai Madhopur":    ["Sawai Madhopur", "Gangapur City", "Bonli", "Wazirpur"],
        "Sikar":             ["Sikar", "Fatehpur", "Laxmangarh", "Neem Ka Thana", "Shrimadhopur"],
        "Sirohi":            ["Sirohi", "Abu Road", "Mount Abu", "Pindwara", "Sheoganj"],
        "Sri Ganganagar":    ["Sri Ganganagar", "Suratgarh", "Padampur", "Raisinghnagar", "Anoopgarh"],
        "Tonk":              ["Tonk", "Deoli", "Malpura", "Uniara", "Todaraisingh"],
        "Udaipur":           ["Udaipur", "Salumbar", "Mavli", "Vallabh Nagar", "Kherwara"],
    },

    # ── Madhya Pradesh (55 districts) ───────────────────────────────────────
    "Madhya Pradesh": {
        "Agar Malwa":         ["Agar", "Susner", "Nalkheda"],
        "Alirajpur":          ["Alirajpur", "Jobat", "Katthiwada"],
        "Anuppur":            ["Anuppur", "Kotma", "Pushparajgarh"],
        "Ashoknagar":         ["Ashoknagar", "Chanderi", "Mungaoli"],
        "Balaghat":           ["Balaghat", "Waraseoni", "Lamta", "Katangi", "Kirnapur"],
        "Barwani":            ["Barwani", "Sendhwa", "Rajpur", "Pati"],
        "Betul":              ["Betul", "Multai", "Amla", "Bhainsdehi"],
        "Bhind":              ["Bhind", "Gohad", "Lahar", "Mehgaon"],
        "Bhopal":             ["Bhopal", "Berasia", "Phanda", "Kolar Road", "Mandideep"],
        "Burhanpur":          ["Burhanpur", "Nepanagar", "Shahpur"],
        "Chhatarpur":         ["Chhatarpur", "Nowgong", "Bijawar", "Harpalpur"],
        "Chhindwara":         ["Chhindwara", "Sausar", "Amarwara", "Pandhurna", "Parasia"],
        "Damoh":              ["Damoh", "Patharia", "Hatta", "Patera"],
        "Datia":              ["Datia", "Sewda", "Seondha"],
        "Dewas":              ["Dewas", "Sonkatch", "Hatpipliya", "Bagli"],
        "Dhar":               ["Dhar", "Manawar", "Sardarpur", "Kukshi", "Badnawar"],
        "Dindori":            ["Dindori", "Shahpura", "Amarpur", "Karanjia"],
        "Guna":               ["Guna", "Raghogarh", "Ashok Nagar (G)"],
        "Gwalior":            ["Gwalior", "Morar", "Lashkar", "Bhitarwar"],
        "Harda":              ["Harda", "Timarni", "Khirkhiya"],
        "Hoshangabad":        ["Hoshangabad", "Itarsi", "Pipariya", "Sohagpur", "Babai"],
        "Indore":             ["Indore", "Mhow", "Sanwer", "Depalpur", "Hatod"],
        "Jabalpur":           ["Jabalpur", "Katni (J)", "Sihora", "Patan", "Murwara"],
        "Jhabua":             ["Jhabua", "Thandla", "Petlawad", "Ranapur"],
        "Katni":              ["Katni", "Mudwara", "Vijayraghavgarh", "Rithi"],
        "Khandwa":            ["Khandwa", "Burhanpur (K)", "Pandhana", "Khalwa"],
        "Khargone":           ["Khargone", "Barwaha", "Bhikangaon", "Maheshwar"],
        "Maihar":             ["Maihar", "Nagod", "Uchhahara"],
        "Mandla":             ["Mandla", "Mawai", "Nainpur", "Bichhia"],
        "Mandsaur":           ["Mandsaur", "Neemuch", "Sitamau", "Garoth"],
        "Morena":             ["Morena", "Ambah", "Joura", "Sabalgarh"],
        "Mauganj":            ["Mauganj", "Deotalab", "Naigarhi"],
        "Narsinghpur":        ["Narsinghpur", "Gadarwara", "Kareli", "Gotegaon"],
        "Neemuch":            ["Neemuch", "Manasa", "Jawad", "Rampura"],
        "Niwari":             ["Niwari", "Orchha", "Prithvipur"],
        "Panna":              ["Panna", "Pawai", "Ajaigarh"],
        "Raisen":             ["Raisen", "Obedullaganj", "Begumganj", "Udaipura"],
        "Rajgarh":            ["Rajgarh", "Narsinghgarh", "Biaora", "Khilchipur"],
        "Ratlam":             ["Ratlam", "Jaora", "Sailana", "Alot"],
        "Rewa":               ["Rewa", "Mauganj (R)", "Sirmaur", "Hanumana"],
        "Sagar":              ["Sagar", "Rehli", "Banda (M)", "Khurai", "Garhakota"],
        "Satna":              ["Satna", "Rewa (S)", "Maihar (S)", "Amarpatan"],
        "Sehore":             ["Sehore", "Ashta", "Budhni", "Ichhawar"],
        "Seoni":              ["Seoni", "Lakhnadon", "Ghansour", "Barghat"],
        "Shahdol":            ["Shahdol", "Annupur", "Jaisinghnagar", "Beohari"],
        "Shahjapur":          ["Shahjapur", "Shujalpur", "Kalapipal", "Maksi"],
        "Sheopur":            ["Sheopur", "Vijaypur", "Karahal"],
        "Shivpuri":           ["Shivpuri", "Pichhore", "Kolaras", "Karera"],
        "Sidhi":              ["Sidhi", "Singrauli (S)", "Majhauli"],
        "Singrauli":          ["Singrauli", "Waidhan", "Chitrangi"],
        "Tikamgarh":          ["Tikamgarh", "Jatara", "Prithvipur (T)", "Baldeogarh"],
        "Ujjain":             ["Ujjain", "Barnagar", "Nagda", "Mahidpur"],
        "Umaria":             ["Umaria", "Bandhogarh", "Pali (U)"],
        "Vidisha":            ["Vidisha", "Ganj Basoda", "Sironj", "Kurwai"],
    },

    # ── Uttar Pradesh (75 districts) ─────────────────────────────────────────
    "Uttar Pradesh": {
        "Lucknow":                ["Lucknow", "Gomti Nagar", "Hazratganj", "Indira Nagar", "Aliganj", "Alambagh", "Charbagh"],
        "Kanpur Nagar":           ["Kanpur", "Armapur", "Kidwai Nagar", "Chakeri", "Kalyanpur"],
        "Kanpur Dehat":           ["Akbarpur", "Rspur", "Ghatampur", "Bhognipur"],
        "Agra":                   ["Agra", "Fatehpur Sikri", "Firozabad (A)"],
        "Firozabad":              ["Firozabad", "Shikohabad", "Tundla", "Jasrana"],
        "Mathura":                ["Mathura", "Vrindavan", "Govardhan", "Mant"],
        "Aligarh":                ["Aligarh", "Atrauli", "Khair", "Iglas"],
        "Hathras":                ["Hathras", "Sadabad", "Sikandra Rao"],
        "Kasganj":                ["Kasganj", "Patiyali", "Amanpur", "Soron"],
        "Etah":                   ["Etah", "Jalesar", "Awagarh", "Marhara"],
        "Mainpuri":               ["Mainpuri", "Shikohabad (M)", "Karhal", "Kishni"],
        "Etawah":                 ["Etawah", "Jaswantnagar", "Bharthana", "Saifai"],
        "Auraiya":                ["Auraiya", "Dibiyapur", "Ajitmal", "Bidhuna"],
        "Farrukhabad":            ["Farrukhabad", "Fatehgarh", "Kaimganj", "Shamshabad"],
        "Kannauj":                ["Kannauj", "Rasulabad", "Tirwa", "Talgramau"],
        "Unnao":                  ["Unnao", "Purwa", "Bangarmau", "Safipur"],
        "Rae Bareli":             ["Rae Bareli", "Lalganj", "Salon", "Tiloi"],
        "Sitapur":                ["Sitapur", "Laharpur", "Biswan", "Siddhaur"],
        "Hardoi":                 ["Hardoi", "Sandila", "Shahabad", "Bilgram"],
        "Lakhimpur Kheri":        ["Lakhimpur", "Kheri", "Pallia", "Nighasan", "Kumbhi"],
        "Bahraich":               ["Bahraich", "Nanpara", "Jarwal", "Kaisarganj"],
        "Shrawasti":              ["Bhinga", "Ikauna", "Sirsia"],
        "Balrampur":              ["Balrampur", "Utraula", "Tulsipur", "Gainsari"],
        "Gonda":                  ["Gonda", "Tarabganj", "Colonelganj", "Mankapur"],
        "Siddharthnagar":         ["Siddharthnagar", "Nautanwa", "Shohratgarh", "Bansi"],
        "Basti":                  ["Basti", "Harraiya", "Kaptanganj", "Rudhauli"],
        "Sant Kabir Nagar":       ["Khalilabad", "Mehdawal", "Hainsar Bazar"],
        "Gorakhpur":              ["Gorakhpur", "Gola Gokarannath", "Sahjanwa", "Bansgaon"],
        "Maharajganj":            ["Maharajganj", "Nautanwa (M)", "Siswa Bazar"],
        "Deoria":                 ["Deoria", "Padrauna", "Bhatpar Rani", "Barhaj"],
        "Kushinagar":             ["Kushinagar", "Padrauna (K)", "Tamkuhi Road", "Hata"],
        "Varanasi":               ["Varanasi", "Ramnagar", "Sarnath", "Kashi", "Chaukaghat"],
        "Chandauli":              ["Chandauli", "Mughal Sarai", "Chakar Nagar"],
        "Ghazipur":               ["Ghazipur", "Zahurabad", "Mohammadabad", "Kasimabad"],
        "Mau":                    ["Mau", "Ghosi", "Kopaganj", "Madhuban"],
        "Azamgarh":               ["Azamgarh", "Lalganj (A)", "Phoolpur (A)", "Sagri"],
        "Ballia":                 ["Ballia", "Rasra", "Bansdih", "Sikandarpur"],
        "Jaunpur":                ["Jaunpur", "Mungra Badshahpur", "Kerakat", "Machhalishahar"],
        "Sultanpur":              ["Sultanpur", "Amethi (S)", "Lambhua", "Musafirkhana"],
        "Amethi":                 ["Amethi", "Gauriganj", "Jagdishpur"],
        "Pratapgarh":             ["Pratapgarh", "Patti", "Kunda", "Raniganj (P)"],
        "Kaushambi":              ["Chail", "Manjhanpur", "Sirathu", "Sarai Akil"],
        "Prayagraj":              ["Prayagraj", "Naini", "Jhunsi", "Bamrauli", "Phulpur"],
        "Fatehpur":               ["Fatehpur", "Bindki", "Khaga", "Husainganj"],
        "Chitrakoot":             ["Chitrakoot", "Karwi", "Mau (C)"],
        "Banda":                  ["Banda", "Naraini", "Atarrha", "Baberu"],
        "Hamirpur":               ["Hamirpur", "Rath", "Maudaha", "Sarila"],
        "Mahoba":                 ["Mahoba", "Charkhari", "Kulpahar", "Kabrai"],
        "Jhansi":                 ["Jhansi", "Babina", "Moth", "Mauranipur"],
        "Lalitpur":               ["Lalitpur", "Mehrauni", "Talbehat"],
        "Meerut":                 ["Meerut", "Hapur (M)", "Kithore", "Garh Mukteshwar"],
        "Hapur":                  ["Hapur", "Pilkhuwa", "Garhmukteshwar"],
        "Baghpat":                ["Baghpat", "Baraut", "Khekra"],
        "Ghaziabad":              ["Ghaziabad", "Loni", "Modinagar", "Muradnagar", "Dasna"],
        "Gautam Buddha Nagar":    ["Noida", "Greater Noida", "Dadri", "Jewar"],
        "Bulandshahr":            ["Bulandshahr", "Khurja", "Anupshahr", "Shikarpur"],
        "Aligarh (district)":     ["Aligarh", "Hathras (A)", "Atrauli (D)"],
        "Moradabad":              ["Moradabad", "Amroha", "Sambhal (M)", "Kundarki"],
        "Amroha":                 ["Amroha", "Hasanpur", "Dhanaura", "Gangeshwar"],
        "Sambhal":                ["Sambhal", "Chandausi", "Bahjoi", "Gunnaur"],
        "Rampur":                 ["Rampur", "Milak", "Suar"],
        "Bijnor":                 ["Bijnor", "Nagina", "Najibabad", "Kiratpur"],
        "Muzaffarnagar":          ["Muzaffarnagar", "Shamli (M)", "Budhana", "Khatauli"],
        "Shamli":                 ["Shamli", "Kairana", "Thanabhawan", "Gangoh"],
        "Saharanpur":             ["Saharanpur", "Deoband", "Gangoh", "Behat", "Nakur"],
        "Ayodhya":                ["Ayodhya", "Faizabad", "Bikapur", "Sohawal"],
        "Ambedkar Nagar":         ["Akbarpur", "Tanda", "Jalalpur"],
        "Bareilly":               ["Bareilly", "Pilibhit (B)", "Faridpur", "Nawabganj"],
        "Pilibhit":               ["Pilibhit", "Bisalpur", "Puranpur"],
        "Shahjahanpur":           ["Shahjahanpur", "Powayan", "Tilhar"],
        "Badaun":                 ["Badaun", "Bilsi", "Sahaswan", "Gunnaur (B)"],
        "Muradabad":              ["Muradabad", "Amroha (Mu)"],
    },

    # ── Bihar (38 districts) ────────────────────────────────────────────────
    "Bihar": {
        "Patna":              ["Patna", "Danapur", "Phulwari", "Khagaul", "Fatwa", "Barh", "Bikram"],
        "Nalanda":            ["Bihar Sharif", "Rajgir", "Hilsa", "Asthawan", "Biharsharif"],
        "Gaya":               ["Gaya", "Bodh Gaya", "Sherghati", "Daudnagar", "Tekari"],
        "Jehanabad":          ["Jehanabad", "Makhdumpur", "Kako"],
        "Arwal":              ["Arwal", "Kaler", "Kurtha"],
        "Aurangabad":         ["Aurangabad", "Deo", "Obra", "Nabinagar", "Rafiganj"],
        "Bhojpur":            ["Ara", "Piro", "Bihiya", "Jagdispur"],
        "Buxar":              ["Buxar", "Dumraon", "Brasaur", "Simri"],
        "Rohtas":             ["Sasaram", "Dehri", "Bikramganj", "Nokha", "Bhabua"],
        "Kaimur":             ["Bhabua", "Ramgarh", "Adhaura", "Chainpur"],
        "Saran":              ["Chapra", "Siwan", "Gopalganj", "Dighwara"],
        "Siwan":              ["Siwan", "Maharajganj (B)", "Basantpur", "Darauli"],
        "Gopalganj":          ["Gopalganj", "Kuchaikote", "Hathua", "Barauli"],
        "West Champaran":     ["Bettiah", "Narkatiaganj", "Bagaha", "Raxaul"],
        "East Champaran":     ["Motihari", "Raxaul (E)", "Dhaka", "Chakia"],
        "Sheohar":            ["Sheohar", "Piprahi", "Dumri Katsari"],
        "Sitamarhi":          ["Sitamarhi", "Dumra", "Parihar", "Bajpatti"],
        "Muzaffarpur":        ["Muzaffarpur", "Motipur", "Kanti", "Bochahan"],
        "Vaishali":           ["Hajipur", "Mahua", "Raghopur", "Lalganj (V)"],
        "Samastipur":         ["Samastipur", "Darbhanga (S)", "Pusa", "Rosera"],
        "Darbhanga":          ["Darbhanga", "Benipur", "Kusheshwar Asthan", "Jale"],
        "Madhubani":          ["Madhubani", "Jhanjharpur", "Phulparas", "Laukaha"],
        "Supaul":             ["Supaul", "Chhatapur", "Kishanganj (Su)", "Triveniganj"],
        "Saharsa":            ["Saharsa", "Simri Bakhtiyarpur", "Mahishi", "Sonbarsha"],
        "Madhepura":          ["Madhepura", "Murliganj", "Gamharia", "Purnea (M)"],
        "Purnea":             ["Purnea", "Kasba", "Byasi", "Dhamdaha"],
        "Katihar":            ["Katihar", "Barari", "Manihari", "Naugachia"],
        "Araria":             ["Araria", "Forbesganj", "Jogbani", "Sikti"],
        "Kishanganj":         ["Kishanganj", "Thakurganj", "Bahadurganj", "Dighalbank"],
        "Bhagalpur":          ["Bhagalpur", "Kahalgaon", "Naugachia (B)", "Sultanganj"],
        "Banka":              ["Banka", "Baunsi", "Amarpur", "Katoria"],
        "Munger":             ["Munger", "Jamalpur", "Tarapur"],
        "Lakhisarai":         ["Lakhisarai", "Surajgarha", "Ramgarh Chowk"],
        "Sheikhpura":         ["Sheikhpura", "Barbigha", "Ariyari"],
        "Jamui":              ["Jamui", "Jhajha", "Sikandra", "Chakai"],
        "Nawada":             ["Nawada", "Rajauli", "Warsaliganj", "Akbarpur"],
        "Khagaria":           ["Khagaria", "Gogri", "Mansi", "Chautham"],
        "Begusarai":          ["Begusarai", "Barauni", "Teghra", "Balia (B)", "Bachhwara"],
    },

    # ── West Bengal (23 districts) ───────────────────────────────────────────
    "West Bengal": {
        "Kolkata":                  ["Kolkata", "Salt Lake", "New Town", "Rajarhat", "Behala", "Tollygunge", "Park Street", "Alipore", "Dum Dum"],
        "Howrah":                   ["Howrah", "Uluberia", "Bally", "Domjur", "Panchla", "Andul"],
        "North 24 Parganas":        ["Barasat", "Barrackpore", "Bongaon", "Basirhat", "Habra", "Ashoknagar", "Naihati"],
        "South 24 Parganas":        ["Diamond Harbour", "Canning", "Baruipur", "Kakdwip", "Namkhana", "Sundarban"],
        "Hooghly":                  ["Hooghly", "Chandannagar", "Serampore", "Arambagh", "Tarakeswar", "Uttarpara"],
        "Purba Bardhaman":          ["Bardhaman", "Durgapur", "Asansol (E)", "Raniganj (B)"],
        "Paschim Bardhaman":        ["Asansol", "Raniganj", "Kulti", "Jamuria"],
        "Birbhum":                  ["Suri", "Bolpur", "Rampurhat", "Sainthia", "Sian"],
        "Bankura":                  ["Bankura", "Bishnupur", "Barjora", "Sonamukhi"],
        "Purulia":                  ["Purulia", "Raghunathpur", "Manbazar", "Adra", "Jhalda"],
        "Jhargram":                 ["Jhargram", "Belpahari", "Binpur", "Silda"],
        "Paschim Medinipur":        ["Midnapore", "Kharagpur", "Ghatal", "Debra", "Daspur"],
        "Purba Medinipur":          ["Tamluk", "Haldia", "Contai", "Digha", "Egra"],
        "Murshidabad":              ["Murshidabad", "Baharampur", "Jangipur", "Berhampur", "Lalbag"],
        "Nadia":                    ["Krishnanagar", "Ranaghat", "Nabadwip", "Kalyani", "Chakdaha"],
        "Malda":                    ["Malda", "English Bazar", "Old Malda", "Chanchal", "Gazole"],
        "Uttar Dinajpur":           ["Raiganj", "Islampur", "Dalkhola", "Itahar"],
        "Dakshin Dinajpur":         ["Balurghat", "Gangarampur", "Buniadpur", "Kumarganj"],
        "Darjeeling":               ["Darjeeling", "Siliguri", "Kurseong", "Kalimpong (D)"],
        "Kalimpong":                ["Kalimpong", "Gorubathan", "Pedong"],
        "Jalpaiguri":               ["Jalpaiguri", "Alipurduar (J)", "Dhupguri", "Malbazar"],
        "Alipurduar":               ["Alipurduar", "Falakata", "Kumargram", "Hasimara"],
        "Cooch Behar":              ["Cooch Behar", "Dinhata", "Tufanganj", "Mathabhanga"],
    },

    # ── Odisha (30 districts) ────────────────────────────────────────────────
    "Odisha": {
        "Khordha":            ["Bhubaneswar", "Khordha", "Jatani", "Balianta", "Pipli"],
        "Cuttack":            ["Cuttack", "Choudwar", "Athagarh", "Banki", "Kendrapara (C)"],
        "Jagatsinghpur":      ["Jagatsinghpur", "Paradeep", "Tirtol", "Erasama"],
        "Kendrapara":         ["Kendrapara", "Pattamundai", "Rajnagar", "Aul"],
        "Jajpur":             ["Jajpur", "Jajpur Road", "Byasanagar", "Dharmasala"],
        "Bhadrak":            ["Bhadrak", "Basudevpur", "Chandbali", "Tihidi"],
        "Balasore":           ["Balasore", "Jaleswar", "Nilagiri", "Soro", "Basta"],
        "Mayurbhanj":         ["Baripada", "Rairangpur", "Bahalda", "Karanjia"],
        "Keonjhar":           ["Keonjhar", "Anandpur", "Joda", "Barbil", "Champua"],
        "Dhenkanal":          ["Dhenkanal", "Kamakhyanagar", "Hindol"],
        "Angul":              ["Angul", "Talcher", "Rourkela (A)", "Athmallik"],
        "Sambalpur":          ["Sambalpur", "Burla", "Hirakud", "Kuchinda"],
        "Jharsuguda":         ["Jharsuguda", "Brajarajnagar", "Brajrajnagar"],
        "Sundargarh":         ["Rourkela", "Sundargarh", "Rajgangpur", "Bondamunda"],
        "Bargarh":            ["Bargarh", "Padampur", "Attabira", "Bhatli"],
        "Nuapada":            ["Nuapada", "Khariar", "Komna"],
        "Bolangir":           ["Balangir", "Titlagarh", "Patnagarh", "Kantabanji"],
        "Sonepur":            ["Sonepur", "Binka", "Tarbha"],
        "Boudh":              ["Boudh", "Phulbani", "Baliguda"],
        "Kandhamal":          ["Phulbani", "Baliguda", "G Udayagiri", "Raikia"],
        "Kalahandi":          ["Bhawanipatna", "Junagarh", "Narla", "Dharmagarh"],
        "Nabarangpur":        ["Nabarangpur", "Umerkote", "Raighar", "Chandahandi"],
        "Koraput":            ["Koraput", "Jeypore", "Sunabeda", "Semiliguda"],
        "Malkangiri":         ["Malkangiri", "Chitrakonda", "Kalimela"],
        "Rayagada":           ["Rayagada", "Gunupur", "Padmapur"],
        "Gajapati":           ["Paralakhemundi", "Mohana", "Gumma"],
        "Ganjam":             ["Berhampur", "Chhatrapur", "Aska", "Digapahandi", "Bhanjanagar"],
        "Nayagarh":           ["Nayagarh", "Daspalla", "Khandapada", "Odagaon"],
        "Puri":               ["Puri", "Nirakarpur", "Brahmagiri", "Konark"],
        "Deogarh":            ["Deogarh", "Barkote", "Tileibani"],
    },

    # ── Punjab (23 districts) ────────────────────────────────────────────────
    "Punjab": {
        "Amritsar":                           ["Amritsar", "Attari", "Ajnala", "Beas"],
        "Gurdaspur":                          ["Gurdaspur", "Pathankot", "Batala", "Dhariwal", "Dinanagar"],
        "Pathankot":                          ["Pathankot", "Sujanpur", "Narot Jaimal Singh"],
        "Hoshiarpur":                         ["Hoshiarpur", "Garhshankar", "Dasuya", "Mukerian"],
        "Shaheed Bhagat Singh Nagar":         ["Nawanshahr", "Balachaur", "Rahon", "Banga"],
        "Rupnagar":                           ["Rupnagar", "Anandpur Sahib", "Morinda", "Kiratpur Sahib"],
        "Mohali (SAS Nagar)":                 ["Mohali", "Kharar", "Dera Bassi"],
        "Fatehgarh Sahib":                    ["Fatehgarh Sahib", "Mandi Gobindgarh", "Bassi Pathana", "Amloh"],
        "Ludhiana":                           ["Ludhiana", "Khanna", "Samrala", "Jagraon", "Raikot", "Doraha"],
        "Patiala":                            ["Patiala", "Rajpura", "Nabha", "Sangrur (P)", "Samana"],
        "Sangrur":                            ["Sangrur", "Barnala (S)", "Sunam", "Malerkotla"],
        "Malerkotla":                         ["Malerkotla", "Ahmadgarh", "Dhuri"],
        "Barnala":                            ["Barnala", "Tapa", "Sehna"],
        "Mansa":                              ["Mansa", "Budhlada", "Bareta", "Sardulgarh"],
        "Bathinda":                           ["Bathinda", "Rampura Phul", "Talwandi Sabo", "Maur"],
        "Muktsar":                            ["Muktsar", "Malout", "Gidderbaha", "Lambi"],
        "Fazilka":                            ["Fazilka", "Abohar", "Jalalabad"],
        "Firozpur":                           ["Firozpur", "Zira", "Guru Har Sahai", "Dharamkot"],
        "Tarn Taran":                         ["Tarn Taran", "Patti", "Khem Karan", "Bhikhiwind"],
        "Jalandhar":                          ["Jalandhar", "Nakodar", "Phagwara", "Shahkot", "Nurmahal"],
        "Kapurthala":                         ["Kapurthala", "Sultanpur Lodhi", "Phagwara (K)"],
        "Moga":                               ["Moga", "Baghapurana", "Nihal Singhwala", "Dharamkot (M)"],
        "Ferozepur":                          ["Firozpur", "Zira (Fe)", "Jalalabad (Fe)"],
    },

    # ── Haryana (22 districts) ───────────────────────────────────────────────
    "Haryana": {
        "Ambala":           ["Ambala", "Naraingarh", "Barara", "Shahzadpur"],
        "Panchkula":        ["Panchkula", "Kalka", "Morni", "Raipur Rani"],
        "Yamunanagar":      ["Yamunanagar", "Jagadhri", "Bilaspur", "Radaur"],
        "Kurukshetra":      ["Kurukshetra", "Thanesar", "Pehowa", "Shahabad"],
        "Kaithal":          ["Kaithal", "Kalayat", "Gulha", "Cheeka"],
        "Karnal":           ["Karnal", "Assandh", "Indri", "Nilokheri"],
        "Panipat":          ["Panipat", "Samalkha", "Israna"],
        "Sonipat":          ["Sonipat", "Gohana", "Kharkhoda", "Rai"],
        "Rohtak":           ["Rohtak", "Maham", "Kalanaur", "Sanghi"],
        "Jhajjar":          ["Jhajjar", "Bahadurgarh", "Beri", "Machhrauli"],
        "Gurugram":         ["Gurugram", "Manesar", "Sohna", "Pataudi"],
        "Nuh":              ["Nuh", "Punhana", "Ferozepur Jhirka", "Tauru"],
        "Palwal":           ["Palwal", "Hathin", "Hodel"],
        "Faridabad":        ["Faridabad", "Ballabhgarh", "Tigaon", "Palwal (F)"],
        "Rewari":           ["Rewari", "Dharuhera", "Kosli", "Bawal"],
        "Mahendragarh":     ["Narnaul", "Mahendragarh", "Ateli", "Kanina"],
        "Charkhi Dadri":    ["Charkhi Dadri", "Badhra", "Baund Kalan"],
        "Bhiwani":          ["Bhiwani", "Loharu", "Tosham", "Siwani"],
        "Hisar":            ["Hisar", "Hansi", "Barwala", "Narnaund"],
        "Fatehabad":        ["Fatehabad", "Tohana", "Ratia", "Jakhal"],
        "Sirsa":            ["Sirsa", "Ellenabad", "Dabwali", "Rania"],
        "Jind":             ["Jind", "Safidon", "Narwana", "Julana", "Uchana"],
    },

    # ── Jharkhand (24 districts) ─────────────────────────────────────────────
    "Jharkhand": {
        "Ranchi":                 ["Ranchi", "Hatia", "Kanke", "Namkum", "Bundu", "Mandar"],
        "East Singhbhum":         ["Jamshedpur", "Dhalbhum", "Potka", "Ghatsila", "Baharagora"],
        "West Singhbhum":         ["Chaibasa", "Chakradharpur", "Jamshedpur (W)", "Goilkera"],
        "Seraikela Kharsawan":    ["Seraikela", "Kharsawan", "Rajnagar", "Kuchai"],
        "Dhanbad":                ["Dhanbad", "Sindri", "Jharia", "Baghmara", "Topchanchi"],
        "Bokaro":                 ["Bokaro", "Chas", "Petarbar", "Gomia", "Chandankiyari"],
        "Hazaribagh":             ["Hazaribagh", "Barhi", "Chouparan", "Barkagaon"],
        "Ramgarh":                ["Ramgarh", "Mandu", "Patratu"],
        "Koderma":                ["Koderma", "Jainagar", "Markacho"],
        "Giridih":                ["Giridih", "Bengabad", "Tisri", "Dumri"],
        "Deoghar":                ["Deoghar", "Madhupur", "Mohanpur", "Sarwan"],
        "Jamtara":                ["Jamtara", "Nala", "Narayanpur", "Kundhit"],
        "Dumka":                  ["Dumka", "Jama", "Shikaripara", "Masalia"],
        "Pakur":                  ["Pakur", "Maheshpur", "Hiranpur", "Littipara"],
        "Sahebganj":              ["Sahebganj", "Rajmahal", "Borio", "Taljhari"],
        "Godda":                  ["Godda", "Mahagama", "Sunderpahari"],
        "Gumla":                  ["Gumla", "Chainpur", "Raidih", "Palkot"],
        "Simdega":                ["Simdega", "Kolebe", "Thethaitangar"],
        "Lohardaga":              ["Lohardaga", "Kuru", "Senha"],
        "Khunti":                 ["Khunti", "Torpa", "Karra", "Murhu"],
        "Palamu":                 ["Daltonganj", "Medininagar", "Hussainabad", "Lesliganj"],
        "Latehar":                ["Latehar", "Chandwa", "Balumath", "Manika"],
        "Chatra":                 ["Chatra", "Simaria", "Itkhori", "Pratappur"],
        "Garhwa":                 ["Garhwa", "Ranka", "Bhandaria", "Nagar Untari"],
    },

    # ── Chhattisgarh (33 districts) ──────────────────────────────────────────
    "Chhattisgarh": {
        "Raipur":                               ["Raipur", "Gariaband", "Baloda Bazar", "Abhanpur"],
        "Baloda Bazar":                         ["Baloda Bazar", "Bhatapara", "Palari"],
        "Gariaband":                            ["Gariaband", "Rajim", "Mainpur"],
        "Mahasamund":                           ["Mahasamund", "Basna", "Pithora", "Saraipali"],
        "Dhamtari":                             ["Dhamtari", "Kurud", "Nagri", "Sihawa"],
        "Durg":                                 ["Durg", "Bhilai", "Patan", "Balod (D)"],
        "Balod":                                ["Balod", "Dongargarh", "Gurur", "Gunderdehi"],
        "Rajnandgaon":                          ["Rajnandgaon", "Dongargarh (R)", "Chhuriya", "Mohla"],
        "Khairagarh-Chhuikhadan-Gandai":        ["Khairagarh", "Chhuikhadan", "Gandai"],
        "Mohla-Manpur-Ambagarh Chouki":         ["Mohla", "Manpur", "Ambagarh Chouki"],
        "Kabirdham":                            ["Kawardha", "Pandariya", "Bodla"],
        "Bemetara":                             ["Bemetara", "Berla", "Saja"],
        "Bilaspur":                             ["Bilaspur", "Masturi", "Takhatpur", "Mungeli (B)"],
        "Gaurela-Pendra-Marwahi":               ["Gaurela", "Pendra", "Marwahi"],
        "Mungeli":                              ["Mungeli", "Lormi", "Patharia"],
        "Raigarh":                              ["Raigarh", "Sarangarh", "Gharghoda", "Lailunga"],
        "Sarangarh-Bilaigarh":                  ["Sarangarh", "Bilaigarh"],
        "Sakti":                                ["Sakti", "Janjgir", "Chanpa"],
        "Janjgir-Champa":                       ["Janjgir", "Champa", "Sakti (J)", "Akaltara"],
        "Korba":                                ["Korba", "Katghora", "Pali (C)"],
        "Korea":                                ["Baikunthpur", "Manendragarh", "Janakpur"],
        "Manendragarh-Chirmiri-Bharatpur":      ["Manendragarh", "Chirmiri", "Bharatpur"],
        "Surguja":                              ["Ambikapur", "Lundra", "Udaipur (C)"],
        "Surajpur":                             ["Surajpur", "Pratappur", "Premnagar"],
        "Balrampur":                            ["Balrampur", "Ramanujganj", "Shankargarh (C)"],
        "Jashpur":                              ["Jashpur", "Pathalgaon", "Bagicha"],
        "Kondagaon":                            ["Kondagaon", "Keshkal", "Narayanpur (C)"],
        "Kanker":                               ["Kanker", "Antagarh", "Bhanupratappur"],
        "Narayanpur":                           ["Narayanpur", "Orcha"],
        "Bastar":                               ["Jagdalpur", "Bastar", "Tokapal"],
        "Dantewada":                            ["Dantewada", "Geedam", "Bacheli"],
        "Sukma":                                ["Sukma", "Konta", "Chhindgarh"],
        "Bijapur":                              ["Bijapur", "Bhairamgarh", "Usur"],
    },

    # ── Assam (35 districts) ────────────────────────────────────────────────
    "Assam": {
        "Kamrup Metro":                  ["Guwahati", "Dispur", "Jalukbari", "Maligaon", "Sonapur", "North Guwahati"],
        "Kamrup":                        ["Hajo", "Palashbari", "Rangia", "Boko", "Chamaria"],
        "Bajali":                        ["Patacharkuchi", "Barpeta Road", "Sorbhog"],
        "Barpeta":                       ["Barpeta", "Sarbhog", "Pathsala"],
        "Nalbari":                       ["Nalbari", "Tihu", "Belsor"],
        "Tamulpur":                      ["Tamulpur", "Baganpara", "Sualkuchi"],
        "Baksa":                         ["Mushalpur", "Barama", "Goreswar"],
        "Chirang":                       ["Bijni", "Boitamari", "Sidli"],
        "Bongaigaon":                    ["Bongaigaon", "Manikpur", "Bijni (B)"],
        "Kokrajhar":                     ["Kokrajhar", "Gossaigaon", "Titaguri"],
        "Dhubri":                        ["Dhubri", "Bilasipara", "Gauripur", "Chapar"],
        "South Salmara-Mankachar":       ["Mankachar", "Salmara"],
        "Goalpara":                      ["Goalpara", "Dudhnoi", "Lakhipur", "Krishnai"],
        "Kampur":                        ["Kampur", "Roha"],
        "Morigaon":                      ["Morigaon", "Jagiroad", "Laharighat"],
        "Nagaon":                        ["Nagaon", "Lumding", "Hojai", "Lanka", "Dhing"],
        "Hojai":                         ["Hojai", "Lumding (H)", "Lanka (H)"],
        "Sonitpur":                      ["Tezpur", "Dhekiajuli", "Sootea", "Gohpur", "Biswanath (S)"],
        "Biswanath":                     ["Biswanath Chariali", "Behali", "Gohpur (B)"],
        "Darrang":                       ["Mangaldoi", "Kalaigaon", "Dalgaon", "Sipajhar"],
        "Lakhimpur":                     ["North Lakhimpur", "Dhakuakhana", "Bihpuria"],
        "Dhemaji":                       ["Dhemaji", "Jonai", "Silapathar"],
        "Majuli":                        ["Garamur", "Kamalabari", "Jengraimukh"],
        "Jorhat":                        ["Jorhat", "Mariani", "Titabar", "Teok"],
        "Sibsagar":                      ["Sibsagar", "Nazira", "Sonari", "Amguri"],
        "Charaideo":                     ["Sonari (C)", "Amguri (C)"],
        "Dibrugarh":                     ["Dibrugarh", "Digboi", "Naharkatia", "Moran"],
        "Tinsukia":                      ["Tinsukia", "Doom Dooma", "Margherita", "Makum"],
        "Karbi Anglong":                 ["Diphu", "Hamren", "Bokajan"],
        "West Karbi Anglong":            ["Hamren", "Baithalangso"],
        "Dima Hasao":                    ["Haflong", "Maibong", "Umrangso"],
        "Cachar":                        ["Silchar", "Sonai", "Lakhipur"],
        "Karimganj":                     ["Karimganj", "Nilambazar", "Badarpur"],
        "Hailakandi":                    ["Hailakandi", "Katlicherra", "Algapur"],
        "Udalguri":                      ["Udalguri", "Khoirabari", "Mazbat"],
    },

    # ── Himachal Pradesh (12 districts) ─────────────────────────────────────
    "Himachal Pradesh": {
        "Shimla":       ["Shimla", "Solan", "Kasauli", "Parwanoo", "Rampur", "Rohru"],
        "Solan":        ["Solan", "Baddi", "Nalagarh", "Parwanoo (S)", "Kasauli (S)"],
        "Sirmaur":      ["Nahan", "Paonta Sahib", "Rajgarh", "Sirmour"],
        "Kangra":       ["Dharamsala", "McLeod Ganj", "Palampur", "Nurpur", "Dehra", "Baijnath"],
        "Chamba":       ["Chamba", "Dalhousie", "Bhattiyat", "Churah", "Pangi"],
        "Mandi":        ["Mandi", "Sundernagar", "Jogindernagar", "Rewalsar"],
        "Kullu":        ["Kullu", "Manali", "Bhuntar", "Banjar", "Nagar"],
        "Hamirpur":     ["Hamirpur", "Nadaun", "Sujanpur", "Barsar"],
        "Una":          ["Una", "Mehatpur", "Bangana", "Nangal"],
        "Bilaspur":     ["Bilaspur", "Ghaggas", "Ghumarwin", "Naina Devi"],
        "Kinnaur":      ["Reckong Peo", "Kalpa", "Sangla", "Tapri"],
        "Lahaul Spiti": ["Keylong", "Kaza", "Udaipur (H)"],
    },

    # ── Uttarakhand (13 districts) ───────────────────────────────────────────
    "Uttarakhand": {
        "Dehradun":        ["Dehradun", "Rishikesh", "Doiwala", "Vikasnagar", "Mussoorie", "Clement Town"],
        "Haridwar":        ["Haridwar", "Roorkee", "Laksar", "Manglaur", "Jwalapur"],
        "Nainital":        ["Nainital", "Haldwani", "Ramnagar", "Bhimtal", "Kathgodam", "Lalkua"],
        "Udham Singh Nagar": ["Rudrapur", "Kashipur", "Jaspur", "Sitarganj", "Khatima", "Bajpur"],
        "Almora":          ["Almora", "Ranikhet", "Bhikiyasain", "Dwarahat", "Someshwar"],
        "Bageshwar":       ["Bageshwar", "Kapkot", "Garur", "Kanda"],
        "Chamoli":         ["Gopeshwar", "Chamoli", "Joshimath", "Badrinath", "Karnaprayag"],
        "Champawat":       ["Champawat", "Tanakpur", "Lohaghat", "Purnagiri"],
        "Pauri Garhwal":   ["Pauri", "Kotdwar", "Srinagar (U)", "Lansdowne"],
        "Pithoragarh":     ["Pithoragarh", "Dharchula", "Didihat", "Munsiari", "Berinag"],
        "Rudraprayag":     ["Rudraprayag", "Kedarnath", "Ukhimath", "Agastyamuni"],
        "Tehri Garhwal":   ["Tehri", "Chamba", "Narendra Nagar", "Devprayag", "New Tehri"],
        "Uttarkashi":      ["Uttarkashi", "Barkot", "Dunda", "Gangotri", "Bhatwari"],
    },

    # ── Goa (2 districts) ────────────────────────────────────────────────────
    "Goa": {
        "North Goa": ["Panaji", "Mapusa", "Vasco da Gama", "Calangute", "Anjuna", "Baga", "Candolim", "Porvorim", "Ponda", "Pernem"],
        "South Goa": ["Margao", "Curchorem", "Quepem", "Canacona", "Sanguem", "Ponda (S)"],
    },

    # ── Manipur (16 districts) ───────────────────────────────────────────────
    "Manipur": {
        "Imphal West":     ["Imphal", "Lamphelpat", "Singjamei", "Khurai", "Patsoi"],
        "Imphal East":     ["Porompat", "Heingang", "Andro", "Khundrakpam"],
        "Thoubal":         ["Thoubal", "Wangjing", "Kakching", "Lilong"],
        "Bishnupur":       ["Bishnupur", "Kumbi", "Moirang", "Ningthoukhong"],
        "Kakching":        ["Kakching", "Sugnu", "Wangjing (K)"],
        "Chandel":         ["Chandel", "Moreh", "Chakpikarong"],
        "Tengnoupal":      ["Tengnoupal", "Moreh (T)"],
        "Churachandpur":   ["Churachandpur", "Thanlon", "Singngat", "Saikul"],
        "Pherzawl":        ["Pherzawl", "Tipaimukh"],
        "Kangpokpi":       ["Kangpokpi", "Sadar Hills", "Gamnom"],
        "Senapati":        ["Senapati", "Mao", "Paomata"],
        "Noney":           ["Noney", "Longmai", "Haochong"],
        "Tamenglong":      ["Tamenglong", "Nungba", "Tousem"],
        "Jiribam":         ["Jiribam", "Borobekra"],
        "Ukhrul":          ["Ukhrul", "Kamjong", "Chingai", "Chassad"],
        "Kamjong":         ["Kamjong", "Nungba (K)"],
    },

    # ── Meghalaya (12 districts) ────────────────────────────────────────────
    "Meghalaya": {
        "East Khasi Hills":         ["Shillong", "Cherrapunji", "Mawsynram", "Mawlai"],
        "West Khasi Hills":         ["Nongstoin", "Mairang", "Ranikor"],
        "South West Khasi Hills":   ["Mawkyrwat", "Ranikor (S)"],
        "Eastern West Khasi Hills": ["Mawkyrwat (E)"],
        "Ri Bhoi":                  ["Nongpoh", "Umroi", "Bhoirymbong", "Umiam"],
        "East Jaintia Hills":       ["Khliehriat", "Amlarem"],
        "West Jaintia Hills":       ["Jowai", "Khliehriat (W)"],
        "East Garo Hills":          ["Williamnagar", "Songsak"],
        "West Garo Hills":          ["Tura", "Selsella", "Dalu"],
        "South Garo Hills":         ["Baghmara", "Ampati"],
        "North Garo Hills":         ["Resubelpara", "Mendipathar"],
        "South West Garo Hills":    ["Ampati (S)"],
    },

    # ── Tripura (8 districts) ────────────────────────────────────────────────
    "Tripura": {
        "West Tripura":   ["Agartala", "Bishalgarh", "Mohanpur", "Majlishpur"],
        "Sepahijala":     ["Bishramganj", "Boxanagar", "Jirania", "Sonamura"],
        "Khowai":         ["Khowai", "Teliamura", "Mungiakami"],
        "Gomati":         ["Udaipur", "Amarpur", "Sonamura (G)"],
        "South Tripura":  ["Belonia", "Udaipur (S)", "Sabroom"],
        "Dhalai":         ["Ambassa", "Kamalpur", "Churaibari"],
        "North Tripura":  ["Dharmanagar", "Kailashahar", "Kumarghat"],
        "Unakoti":        ["Kailashahar (U)", "Chandipur", "Kumarghat (U)"],
    },

    # ── Nagaland (16 districts) ──────────────────────────────────────────────
    "Nagaland": {
        "Kohima":          ["Kohima", "Jotsoma", "Viswema", "Khonoma"],
        "Chumoukedima":    ["Chumoukedima", "Seithekema"],
        "Dimapur":         ["Dimapur", "Zubza", "Ganeshnagar"],
        "Niuland":         ["Niuland", "Chumukedima (N)"],
        "Mokokchung":      ["Mokokchung", "Tuli", "Longleng (M)"],
        "Longleng":        ["Longleng", "Tuli (L)", "Jalukie"],
        "Wokha":           ["Wokha", "Sanis", "Bhandari"],
        "Zunheboto":       ["Zunheboto", "Akuluto", "Satakha"],
        "Phek":            ["Phek", "Pfutsero", "Chizami"],
        "Peren":           ["Peren", "Jalukie (P)", "Tening"],
        "Tuensang":        ["Tuensang", "Noksen"],
        "Noklak":          ["Noklak", "Tizit"],
        "Kiphire":         ["Kiphire", "Seyochung", "Shamator"],
        "Shamator":        ["Shamator", "Chare", "Yimkhiong"],
        "Mon":             ["Mon", "Tizit (M)", "Tobu"],
        "Tseminyu":        ["Tseminyu", "Ruzazho"],
    },

    # ── Mizoram (11 districts) ───────────────────────────────────────────────
    "Mizoram": {
        "Aizawl":      ["Aizawl", "Durtlang", "Bawngkawn", "Zemabawk"],
        "Kolasib":     ["Kolasib", "Bilkhawthlir", "Vairengte"],
        "Mamit":       ["Mamit", "Zawlnuam", "West Phaileng"],
        "Champhai":    ["Champhai", "Khawzawl (C)"],
        "Khawzawl":    ["Khawzawl", "Ngopa"],
        "Saitual":     ["Saitual", "Khumtung", "Tlangnuam"],
        "Serchhip":    ["Serchhip", "Thenzawl", "N Vanlaiphai"],
        "Hnahthial":   ["Hnahthial", "East Lungdar"],
        "Lunglei":     ["Lunglei", "Tlabung", "Hnahthial (L)"],
        "Lawngtlai":   ["Lawngtlai", "Sangau", "Chawngte"],
        "Saiha":       ["Saiha", "Tuipang", "Palak"],
    },

    # ── Arunachal Pradesh (25 districts) ────────────────────────────────────
    "Arunachal Pradesh": {
        "Papum Pare":           ["Itanagar", "Naharlagun", "Nirjuli", "Banderdewa"],
        "Kamle":                ["Raga", "Daporijo (K)"],
        "Kra Daadi":            ["Yangte", "Palin"],
        "Kurung Kumey":         ["Koloriang", "Champi"],
        "Lower Subansiri":      ["Ziro", "Hapoli", "Daporijo"],
        "Upper Subansiri":      ["Daporijo", "Siyum"],
        "West Kameng":          ["Bomdila", "Dirang", "Rupa"],
        "Tawang":               ["Tawang", "Mukto", "Jang"],
        "East Kameng":          ["Seppa", "Pakke-Kessang (E)"],
        "Pakke-Kessang":        ["Palin (P)", "Seijosa"],
        "Lepa Rada":            ["Basar", "Liromoba"],
        "Lower Siang":          ["Likabali", "Nari"],
        "Shi Yomi":             ["Tato", "Mechuka"],
        "Siang":                ["Boleng", "Pangin"],
        "Upper Siang":          ["Yingkiong", "Jengging", "Geku"],
        "East Siang":           ["Pasighat", "Nari (E)", "Sibsagar (A)"],
        "Lohit":                ["Tezu", "Namsai (L)", "Hayuliang"],
        "Namsai":               ["Namsai", "Chongkham"],
        "Anjaw":                ["Hawai", "Hayuliang (A)"],
        "Lower Dibang Valley":  ["Roing", "Hunli"],
        "Dibang Valley":        ["Anini", "Mipi"],
        "Changlang":            ["Changlang", "Miao", "Jairampur", "Nampong"],
        "Tirap":                ["Khonsa", "Deomali", "Lazu"],
        "Longding":             ["Longding", "Wakka", "Pumao"],
        "Itanagar Capital Complex": ["Itanagar", "Naharlagun", "Nirjuli"],
    },

    # ── Sikkim (6 districts) ────────────────────────────────────────────────
    "Sikkim": {
        "East Sikkim":   ["Gangtok", "Singtam", "Rangpo", "Ranipool", "Rongli"],
        "Pakyong":       ["Pakyong", "Rhenock", "Ravangla (P)"],
        "West Sikkim":   ["Gyalshing", "Jorethang", "Nayabazar", "Soreng (W)"],
        "Soreng":        ["Soreng", "Chakung", "Timburbong"],
        "North Sikkim":  ["Mangan", "Lachen", "Lachung", "Chungthang"],
        "South Sikkim":  ["Namchi", "Ravangla", "Jorethang (S)", "Melli"],
    },

    # ── Delhi (11 districts) ────────────────────────────────────────────────
    "Delhi": {
        "Central Delhi":     ["Connaught Place", "Karol Bagh", "Daryaganj", "Paharganj", "Sadar Bazaar"],
        "North Delhi":       ["Civil Lines", "Sadar Bazar", "Model Town", "Roshanara", "Timarpur"],
        "South Delhi":       ["Saket", "Vasant Kunj", "Hauz Khas", "Mehrauli", "Malviya Nagar", "Lajpat Nagar", "Greater Kailash", "Kalkaji", "Okhla"],
        "East Delhi":        ["Laxmi Nagar", "Preet Vihar", "Patparganj", "Mayur Vihar", "Shahdara", "Krishna Nagar"],
        "West Delhi":        ["Janakpuri", "Uttam Nagar", "Vikaspuri", "Tilak Nagar", "Rajouri Garden", "Subhash Nagar"],
        "North East Delhi":  ["Dilshad Garden", "Johri Enclave", "Nand Nagari", "Seelampur", "Mustafabad"],
        "North West Delhi":  ["Pitampura", "Rohini", "Shalimar Bagh", "Paschim Vihar", "Mangolpuri"],
        "South West Delhi":  ["Dwarka", "Palam", "Inderpuri", "Dabri", "Bindapur"],
        "New Delhi":         ["Connaught Place", "Lodhi Road", "Khan Market", "Chanakyapuri", "Safdarjung"],
        "Shahdara":          ["Karkardooma", "Anand Vihar", "Vivek Vihar", "Dilshad Garden (S)"],
        "South East Delhi":  ["Okhla", "Tughlakabad", "Badarpur", "Sangam Vihar"],
    },

    # ── Jammu & Kashmir (20 districts) ───────────────────────────────────────
    "Jammu & Kashmir": {
        "Srinagar":     ["Srinagar", "Ganderbal", "Budgam", "Dal Lake", "Pampore"],
        "Ganderbal":    ["Ganderbal", "Kangan", "Wakura", "Lar"],
        "Budgam":       ["Budgam", "Chadoora", "Narbal", "Sopore (B)"],
        "Anantnag":     ["Anantnag", "Bijbehara", "Qazigund", "Pahalgam", "Dooru"],
        "Kulgam":       ["Kulgam", "Yaripora", "Qaimoh"],
        "Shopian":      ["Shopian", "Kellar", "Hirpora"],
        "Pulwama":      ["Pulwama", "Tral", "Pampore (P)", "Awantipora"],
        "Baramulla":    ["Baramulla", "Sopore", "Uri", "Rafiabad", "Tangmarg"],
        "Bandipore":    ["Bandipora", "Gurez", "Sumbal"],
        "Kupwara":      ["Kupwara", "Handwara", "Karnah"],
        "Jammu":        ["Jammu", "Samba", "Domana", "Nagrota", "Bishnah"],
        "Samba":        ["Samba", "Vijaypur", "Ghagwal"],
        "Kathua":       ["Kathua", "Hiranagar", "Billawar", "Basohli"],
        "Udhampur":     ["Udhampur", "Ramnagar (J)", "Chenani"],
        "Reasi":        ["Reasi", "Arnas", "Mahore"],
        "Ramban":       ["Ramban", "Banihal", "Gool"],
        "Doda":         ["Doda", "Bhaderwah", "Thathri", "Gandoh"],
        "Kishtwar":     ["Kishtwar", "Paddar", "Chatroo", "Marwah"],
        "Poonch":       ["Poonch", "Surankote", "Mandi (P)"],
        "Rajouri":      ["Rajouri", "Nowshera", "Kalakote", "Thannamandi"],
    },

    # ── Ladakh (2 districts) ────────────────────────────────────────────────
    "Ladakh": {
        "Leh":    ["Leh", "Diskit", "Khaltsi", "Khaldse", "Nyoma", "Nubra"],
        "Kargil": ["Kargil", "Zanskar", "Drass", "Sankoo", "Padum"],
    },

    # ── Chandigarh (UT) ─────────────────────────────────────────────────────
    "Chandigarh": {
        "Chandigarh": ["Chandigarh", "Sector 17", "Sector 22", "Sector 35", "Mani Majra", "Industrial Area"],
    },

    # ── Puducherry (4 districts) ─────────────────────────────────────────────
    "Puducherry": {
        "Puducherry":  ["Puducherry", "Oulgaret", "Ariyankuppam", "Bahour", "Villianur"],
        "Karaikal":    ["Karaikal", "Thirunallar", "Neravy"],
        "Yanam":       ["Yanam"],
        "Mahe":        ["Mahe"],
    },

    # ── Andaman & Nicobar Islands ────────────────────────────────────────────
    "Andaman & Nicobar Islands": {
        "South Andaman":              ["Port Blair", "Bambooflat", "Prothrapur", "Buniyadabad"],
        "North & Middle Andaman":     ["Mayabunder", "Diglipur", "Rangat", "Kadamtala"],
        "Nicobar":                    ["Car Nicobar", "Nancowry", "Great Nicobar"],
    },

    # ── Dadra & Nagar Haveli and Daman & Diu ────────────────────────────────
    "Dadra & Nagar Haveli and Daman & Diu": {
        "Dadra & Nagar Haveli": ["Silvassa", "Amli", "Khadoli", "Naroli"],
        "Daman":                ["Daman", "Nani Daman", "Moti Daman"],
        "Diu":                  ["Diu", "Fudam", "Ghogla", "Vanakbara"],
    },

    # ── Lakshadweep ─────────────────────────────────────────────────────────
    "Lakshadweep": {
        "Lakshadweep": ["Kavaratti", "Agatti", "Minicoy", "Amini", "Andrott"],
    },
}


class Command(BaseCommand):
    help = "Load complete India location data (all 36 states/UTs, all districts, major cities) into LocationMaster"

    def handle(self, *args, **options):
        self.stdout.write("Clearing existing location data...")
        LocationMaster.objects.all().delete()

        records = []
        for state, districts in INDIA_LOCATIONS.items():
            for district, cities in districts.items():
                if cities:
                    for city in cities:
                        records.append(LocationMaster(state=state, district=district, city=city))
                else:
                    records.append(LocationMaster(state=state, district=district, city=""))

        LocationMaster.objects.bulk_create(records, ignore_conflicts=True)
        total = LocationMaster.objects.count()
        states = LocationMaster.objects.values_list("state", flat=True).distinct().count()
        districts = LocationMaster.objects.values_list("district", flat=True).exclude(district="").distinct().count()

        self.stdout.write(self.style.SUCCESS(
            f"Successfully loaded {total} location records "
            f"({states} states/UTs, {districts} districts)"
        ))
