# Generated by Django 5.2.14 on 2026-06-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_plan_store_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='movement_log_retention_days',
            field=models.PositiveIntegerField(default=90, help_text='0 = permanent. How far back vendor can view movement history.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='po_limit_monthly',
            field=models.PositiveIntegerField(default=5, help_text='0 = unlimited. Max purchase orders per calendar month.'),
        ),
        migrations.AddField(
            model_name='plan',
            name='supplier_limit',
            field=models.PositiveIntegerField(default=3, help_text='0 = unlimited. Max suppliers the vendor can add.'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('topup', 'Wallet Top-up'), ('subscription', 'Subscription Purchase'), ('refund', 'Refund'), ('referral', 'Referral Reward')], max_length=20),
        ),
    ]
