# Generated by Django 5.2.14 on 2026-06-29 12:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0009_add_blacklisted_status_and_inventory_fields'),
        ('stores', '0021_add_vendor_type_home_based_service_catalogue'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockAudit',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=15)),
                ('items', models.JSONField(default=list, help_text='[{variant_id, sku, system_qty, counted_qty, discrepancy}]')),
                ('total_discrepancy', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('conducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_audits', to='stores.store')),
            ],
            options={
                'db_table': 'inv_stock_audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('whatsapp', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('product_categories', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='stores.store')),
            ],
            options={
                'db_table': 'inv_suppliers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent to Supplier'), ('received', 'Stock Received'), ('cancelled', 'Cancelled')], default='draft', max_length=10)),
                ('items', models.JSONField(default=list, help_text='[{product_id, variant_id, sku, qty, unit_cost}]')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('expected_by', models.DateField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='stores.store')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier')),
            ],
            options={
                'db_table': 'inv_purchase_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompositeProduct',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(help_text='Units of this component per bundle')),
                ('bundle_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_components', to='products.product')),
                ('component_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_bundles', to='products.productvariant')),
            ],
            options={
                'db_table': 'inv_composite_products',
                'unique_together': {('bundle_product', 'component_variant')},
            },
        ),
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=200, unique=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('returned', 'Returned'), ('damaged', 'Damaged')], default='available', max_length=10)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_numbers', to='products.productvariant')),
            ],
            options={
                'db_table': 'inv_serial_numbers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variant', 'status'], name='inv_sn_variant_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockMovementLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_qty', models.PositiveIntegerField()),
                ('new_qty', models.PositiveIntegerField()),
                ('delta', models.IntegerField(help_text='new_qty - old_qty; negative = stock reduced')),
                ('reason', models.CharField(choices=[('manual', 'Manual Update'), ('reservation', 'Reservation Placed'), ('restoration', 'Reservation Cancelled/Expired'), ('invoice', 'Invoice Sale'), ('purchase', 'Purchase Order Received'), ('return', 'Customer Return'), ('damage', 'Damaged / Written Off'), ('correction', 'Stock Audit Correction')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='products.productvariant')),
            ],
            options={
                'db_table': 'inv_stock_movement_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['variant', '-created_at'], name='inv_sml_variant_date_idx'), models.Index(fields=['changed_by', '-created_at'], name='inv_sml_user_date_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockWatchlist',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_stock_watchlist', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inv_watchers', to='products.product')),
            ],
            options={
                'db_table': 'inv_stock_watchlists',
                'unique_together': {('customer', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['store', 'is_active'], name='inv_sup_store_active_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['store', 'status'], name='inv_po_store_status_idx'),
        ),
    ]
