# Generated by Django 5.2.14 on 2026-06-17 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_message', 'New Message'), ('reservation_created', 'Reservation Created'), ('reservation_confirmed', 'Reservation Confirmed'), ('reservation_cancelled', 'Reservation Cancelled'), ('reservation_expired', 'Reservation Expired'), ('reservation_expiring_soon', 'Reservation Expiring Soon'), ('new_follower', 'New Follower'), ('new_review', 'New Review'), ('store_opened', 'Store Opened'), ('new_offer', 'New Offer'), ('video_liked', 'Video Liked'), ('video_ready', 'Video Ready'), ('video_expiring_soon', 'Video Expiring Soon'), ('wallet_topup', 'Wallet Top-Up'), ('subscription_expiring', 'Subscription Expiring'), ('subscription_expired', 'Subscription Expired'), ('group_added', 'Added to Group'), ('group_removed', 'Removed from Group'), ('group_product_shared', 'Product Shared in Group'), ('group_product_finalized', 'Product Finalized in Group'), ('group_admin_promoted', 'Promoted to Group Admin'), ('invoice_received', 'Invoice Received'), ('loyalty', 'Loyalty Points'), ('vendor_coupon', 'Vendor Coupon'), ('weekly_digest', 'Weekly Digest'), ('price_drop_alert', 'Price Drop Alert'), ('referral_reward', 'Referral Reward')], db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'notification_type'], name='notif_recipient_type_idx'),
        ),
    ]
