# Generated by Django 5.2.14 on 2026-05-15 04:30

import django.contrib.gis.db.models.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fashion", "Fashion"),
                            ("jewellery", "Jewellery"),
                            ("footwear", "Footwear"),
                            ("decor", "Home Decor"),
                            ("furniture", "Furniture"),
                            ("gifts", "Gifts"),
                            ("beauty", "Beauty"),
                            ("food", "Food"),
                            ("electronics", "Electronics"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("address", models.TextField()),
                ("locality", models.CharField(blank=True, max_length=200)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("logo_url", models.URLField(blank=True)),
                ("banner_url", models.URLField(blank=True)),
                ("qr_code_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_open", models.BooleanField(default=False)),
                ("performance_score", models.FloatField(default=0.0)),
                (
                    "wallet_balance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "owner",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "stores",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreFollow",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_stores",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_follows",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StoreHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("open_time", models.TimeField()),
                ("close_time", models.TimeField()),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hours",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "store_hours",
                "ordering": ["day"],
            },
        ),
        migrations.CreateModel(
            name="StoreReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rating", models.PositiveSmallIntegerField()),
                ("comment", models.TextField(blank=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="stores.store",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="store_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "store_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(
                fields=["is_active", "is_verified"], name="store_active_verified_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="store",
            index=models.Index(fields=["category"], name="store_category_idx"),
        ),
        migrations.AddIndex(
            model_name="store",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="store_name_gin_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AlterUniqueTogether(
            name="storefollow",
            unique_together={("user", "store")},
        ),
        migrations.AlterUniqueTogether(
            name="storehours",
            unique_together={("store", "day")},
        ),
        migrations.AlterUniqueTogether(
            name="storereview",
            unique_together={("user", "store")},
        ),
    ]
