# Generated by Django 5.2.14 on 2026-05-17 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0002_store_location_geography"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreOffer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "discount_pct",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("valid_till", models.DateField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "store",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="stores.store",
                    ),
                ),
            ],
            options={
                "db_table": "store_offers",
                "ordering": ["-created_at"],
            },
        ),
    ]
