# Generated by Django 5.2.14 on 2026-06-17 14:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_invoice_gst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerblockedstore',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
