# Generated by Django 5.2.14 on 2026-06-29 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_perf_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_home_based',
            field=models.BooleanField(default=False, help_text='If True: address hidden publicly, shown only after accepted visit reservation.'),
        ),
        migrations.AddField(
            model_name='store',
            name='vendor_type',
            field=models.CharField(choices=[('product', 'Product Vendor'), ('service', 'Service Vendor')], default='product', help_text='PRODUCT = sells physical goods with inventory. SERVICE = provides skills/time with service catalogue.', max_length=10),
        ),
        migrations.CreateModel(
            name='ServiceCatalogue',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220)),
                ('description', models.TextField(blank=True)),
                ('price_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='Estimated service duration in minutes', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('image_url', models.URLField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='stores.store')),
            ],
            options={
                'db_table': 'service_catalogue',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('store', 'slug')},
            },
        ),
    ]
