# Generated by Django 5.2.14 on 2026-06-17 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_perf_indexes'),
        ('reservations', '0004_reservation_cancel_reason'),
        ('stores', '0020_perf_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['created_at'], name='res_created_at_idx'),
        ),
    ]
